[package]
name = "meowlist"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs-next = "2.0.0"
glib-macros = "0.20.7"
gtk = { version = "0.9.5", package = "gtk4", features = ["v4_16"] }
rusqlite = "0.32.1"
