[package]
name = "meowlist"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.26", features = ["derive"]}
colored = "3.0.0"
serde = { version = "1.0.217", features = ["derive"]}
serde_json = "1.0.135"
dirs-next = "2.0"
rusqlite = "0.32.1"
